# Generated by Django 4.2.19 on 2025-04-19 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viagem', '0001_initial'),
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='viagem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='viagem.viagem'),
            preserve_default=False,
        ),
    ]
