# Generated by Django 4.2.19 on 2025-04-18 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Desativado')], max_length=30)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lazer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('preco', models.FloatField()),
                ('tempo', models.IntegerField(null=True)),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viagem.espaco')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEspaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Desativado')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoLazer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Desativado')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Desativado')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('data_de_viagem', models.DateField()),
                ('tempo_a_fazer', models.IntegerField()),
                ('data_regresso', models.DateField()),
                ('status_ative', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Desativado')], max_length=30)),
                ('status_selected', models.CharField(choices=[('rejected', 'Rejeitado'), ('accepted', 'Aceite')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Desativado')], max_length=30)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('tipo_de_zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viagem.tipozona')),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('orcamento', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('lazer1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lazer_1', to='viagem.lazer')),
                ('lazer2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lazer_2', to='viagem.lazer')),
                ('lazer3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lazer_3', to='viagem.lazer')),
                ('viagem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viagem.viagem')),
            ],
        ),
        migrations.AddField(
            model_name='lazer',
            name='tipo_de_lazer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viagem.tipolazer'),
        ),
        migrations.AddField(
            model_name='espaco',
            name='tipo_de_espaco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viagem.tipoespaco'),
        ),
        migrations.AddField(
            model_name='espaco',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viagem.zona'),
        ),
    ]
